spring:
  data:
    mongodb:
      uri:
      database:
      auto-index-creation:

  redis:
    host:
    port:
    password:

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:


server:
  port:

jwt:
  secretKey:


cloudinary:
  cloud_name:
  api_key:
  api_secret:


spring.servlet.multipart.enabled:
spring.servlet.multipart.max-file-size:
spring.servlet.multipart.max-request-size:

frontend: