spring:
  data:
    mongodb:
      uri: mongodb+srv://sarkarrishiraj475:uIQU1JFL9Q6tAmOK@cluster0.o6lmh.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: elearningwebsite
      auto-index-creation: true

  redis:
    host: redis-12716.c212.ap-south-1-1.ec2.redns.redis-cloud.com
    port: 12716
    password: q4PCoaO5ZAshNoKpI3YcuV9iDwzKCLwC

server:
  port: 8080

jwt:
  secretKey: jVF7qP9RzxE7gvHqXS3qQzGw2U9XzqP7vNs8xK2nLwM=


cloudinary:
  cloud_name: backendpractice
  api_key: 587564948549994
  api_secret: zY7EQnDOCoop7ucttWRACVkmBxU


spring.servlet.multipart.enabled: true
spring.servlet.multipart.max-file-size: 2MB
spring.servlet.multipart.max-request-size: 2MB

frontend: http://localhost:5173